### ISSUE TITLE
Docker container Fedora version + Questions

### ISSUE THREAD

**Issue by a-nldisr** [kubevirt/vAdvisor#15]
Hi, 

First of all, im sorry to ask a question here. Looked for a google group but couldn't find something, sorry if i missed it! To polute the issue tracker as little as possible i added a question about GPU.

We are using vAdvisor to keep an eye on our virtual machine metrics, besides offering simple compute resources we also offer GPU's with VFIO-pci. Are there any plans to expose these metrics, i expect its hard to gather these metrics since we have to blacklist the devices to ensure its not used by the host. 

Second question is: Current version of the Dockerfile is running on Fedora 23, i tried to quick and dirty update to a Fedora 26 version and try to update the dependencies but ran into issues. I get the Dockerfile to work again, but all some of the metrics are not generated and there is nothing in the docker logs. Output we get:

<pre>
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 397488128.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 48128000.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1510065749.48
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1.12
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 17.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 65536.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="6",patchlevel="2",version="3.6.2"} 1.0
# HELP vm_up 0 if the VM is down, 1 if the VM is up and running, other states
# TYPE vm_up gauge
# HELP vm_cpu_milliseconds_total Overall VM CPU time in milliseconds
# TYPE vm_cpu_milliseconds_total counter
# HELP vm_cpu_system_milliseconds_total Overall VM System CPU time in milliseconds
# TYPE vm_cpu_system_milliseconds_total counter
# HELP vm_cpu_user_milliseconds_total Overall VM User CPU time in milliseconds
# TYPE vm_cpu_user_milliseconds_total counter
# HELP vm_memory_bytes VM Memory in bytes
# TYPE vm_memory_bytes gauge
# HELP vm_network_receive_bytes_total Cumulative count of bytes received
# TYPE vm_network_receive_bytes_total counter
# HELP vm_network_receive_packets_total Cumulative count of packets received
# TYPE vm_network_receive_packets_total counter
# HELP vm_network_receive_dropped_packets_total Cumulative count of packets dropped while receiving
# TYPE vm_network_receive_dropped_packets_total counter
# HELP vm_network_receive_errors_total Cumulative count of errors encountered while receiving
# TYPE vm_network_receive_errors_total counter
# HELP vm_network_transmit_bytes_total Cumulative count of bytes transmitted
# TYPE vm_network_transmit_bytes_total counter
# HELP vm_network_transmit_packets_total Cumulative count of packets transmitted
# TYPE vm_network_transmit_packets_total counter
# HELP vm_network_transmit_dropped_packets_total Cumulative count of packets dropped while transmitting
# TYPE vm_network_transmit_dropped_packets_total counter
# HELP vm_network_transmit_errors_total Cumulative count of errors encountered while transmitting
# TYPE vm_network_transmit_errors_total counter
# HELP vm_disk_write_requests_total Cumulative count of disk write requests
# TYPE vm_disk_write_requests_total counter
# HELP vm_disk_write_bytes_total Cumulative count of disk writes in bytes
# TYPE vm_disk_write_bytes_total counter
# HELP vm_disk_read_requests_total Cumulative count of disk read requests
# TYPE vm_disk_read_requests_total counter
# HELP vm_disk_read_bytes_total Cumulative count of disk reads in bytes
# TYPE vm_disk_read_bytes_total counter
# HELP vm_vcpu_milliseconds_total Overall CPU time on the virtual CPU in milliseconds
# TYPE vm_vcpu_milliseconds_total counter
</pre>

 Are there any plans to update the project?

Adjusted the Dockerfile i used to build image as txt. Had to make some quick adjustments.

Got it working by eventually pip3 install gevent. The wheel file gevent-1.2.2-cp34-cp34m-manylinux1_x86_64.whl gave an error that the platform was not supported. Since a simple pip install gave gevent 1.2.2 by default.

The geventhttpclient required gcc, redhat-rpm-config, python3-devel. 

[Dockerfile.txt](https://github.com/kubevirt/vAdvisor/files/1453259/Dockerfile.txt)

**Comment by a-nldisr** [comment]
You can check Dockerfile also here: 
a-nldisr/vAdvisor@073a56e05eb766e5404ba32f1143536afcd04f23
Build on Docker hub: 
anldisr/vadvisor:latest

**Comment by rmohr** [comment]
Hi @a-nldisr,

Sorry for the late response. Right now it does not look like we will maintain or keep this app for long. There might be a rewrite in Go with similar or less features (mostly focus on Prometheus). It is also not yet clear, if KubeVirt will continue using libvirt. So a lot of question marks regarding to this app. I would not count too much on it.

**Comment by a-nldisr** [comment]
Thats a shame, thanks for the answer
